# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter_article', '0002_auto_20180712_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_dzs',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_type_id',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='user_id',
        ),
    ]
